package.json

fix(deploy): use nodejs:10 continer

---

package-lock.json
package.json

Greenkeeper/@adobe/helix shared 1.0.1

---

package-lock.json
package.json

Greenkeeper/googleapis 39.2.0

---

package-lock.json
package.json

Greenkeeper/codecov 3.4.0

---

package-lock.json
package.json

Greenkeeper/codecov 3.5.0

---

src/status.js
test/testStatus.js

Performs basic probing of the three main API endpoints, then responds with Pingdom-compatible API status
fixes #19

feat(monitoring): report status to Pingdom

---

build/prepare.js

Adding Prepare

---

package-lock.json
package.json

Greenkeeper/@adobe/openwhisk action builder 1.1.1

---

package-lock.json
package.json

Greenkeeper/mocha 6.2.0

---

package-lock.json
package.json

Greenkeeper/@google cloud/bigquery 4.1.5

---

package-lock.json
package.json

Greenkeeper/snyk 1.194.0

---

package-lock.json
package.json

Greenkeeper/snyk 1.198.0

---

README.md
src/index.js
test/testAddlogger.js
test/testFastlyLogs.js
test/testGoogleAuth.js
test/testGoogleBigquery.js
test/testGoogleIAM.js

fix(params): rename google specific params

---

package-lock.json
package.json

Greenkeeper/@adobe/helix pingdom status 3.1.1

---

.snyk
package.json

build(snyk): remove snyk

---

src/index.js

better fastly API endpoint for status checks

---

.circleci/config.yml
package-lock.json
package.json
src/index.js

Use the new `helix-status` library and automatically install the check

New status

---

package-lock.json
package.json

Greenkeeper/nock 11.3.2

---

package-lock.json
package.json

Greenkeeper/epsagon 1.33.3

---

README.md
src/addlogger.js
src/fastly/logs.js

Hi there, 
I updated the error messages as well as this repo's README for consistency purposes, and updated some spelling/grammar mistakes found also.
Hope this helps!

Updated error messages and README.

---

src/addlogger.js

feat(addLogger): adapt to VCL change (adobe/helix-publish#384)

---

README.md
src/addlogger.js
src/coralogix/schema.js
src/fastly/logs.js
src/google/schema.js
src/index.js
src/util/schemahelper.js
test/testAddlogger.js
test/testSchemaHelper.js

support for Coralogix 

---

src/coralogix/schema.js
src/google/schema.js

feat: log vcl trace to support post mortem incident analysis

---

package.json

ci(deploy): use correct status check

---

src/coralogix/schema.js

feat(coralogix): support outer cdns

---

src/google/schema.js

addsf fallbacks for helix-specific properties that have a non-helix equivalent

feat(google): support outer cdns

---

src/coralogix/schema.js

fix(schema): fix cache status (#322)

---

.circleci/config.yml
test/testPostdeployPreprod.js

test(post-deploy): add preprod test

---

src/coralogix/schema.js

previously, the query string was not included

fix(coralogix): log complete request uri

---

test/testGoogleBigquery.js

test(bigquery): test additional error case

---

package-lock.json
package.json
src/google/iam.js

Use helix fetch

---

src/addlogger.js
src/coralogix/logger.js
src/google/logger.js
test/testAddlogger.js

Refactor: Pluggable loggers

---

src/addlogger.js
src/index.js
src/splunk/logger.js

Fix missing Splunk log invocation

---

src/coralogix/schema.js
src/index.js

- feat(logging): report errors in x-error header
- feat(coralogix): log x-error header to coralogix

log x error

---

src/coralogix/schema.js
src/fastly/logs.js

More log fixes

---

src/coralogix/schema.js

feat: log fastly.error

---

tools/bulk-logger.sh

fix(bulk): add a version comment to the VCL version

---

src/coralogix/schema.js

feat: log client.ip

---

.circleci/config.yml

@stefan-guggisberg feel free to merge if you really don't want the automatic updates.

ci(skyline): disable automatic skyline log updates

---

src/coralogix/schema.js

log X-BYO-CDN-Type request header

---

.circleci/config.yml

- ci(circleci): replace deprecated image (CircleCI wants this)
- build(deploy): do not deploy to google (Adobe...)

Adjust deployment/CI to recent changes

---

src/coralogix/schema.js

log X-Push-Invalidation
